### ISSUE TITLE
midterm-jpark.py is ready for grading

### ISSUE THREAD

**Issue by shosking-matc** [madisoncollege-it-programs/python-scripting-shosking-matc#12]

**Comment by cethenmc** [comment]
Really nice work!  Everything functions, as expected.  In the code lines 21 and 24 are going to fire every time in the loop.  You were very specific on the two separate ifs, and you could do an else, so both compares don't fire when the one is met.  Letting that part slide.  However,  Lines 31 - 36 should fall into one if statement without hardcoding.  The evaluation can be done given the input and against the dictionary in a couple of lines (2 pts).  Score 31/33.
