### ISSUE TITLE
Week 5 File Interaction Ready for Grading

### ISSUE THREAD

**Issue by shosking-matc** [madisoncollege-it-programs/python-scripting-shosking-matc#5]
I'm not entirely sure that I did the 3rd problem correctly

**Comment by cethenmc** [comment]
Spencer - All of the answers are in good shape.  However, for #3, you did not approach the question the way you were asked to derive the answers.  Your answer for #3 is not following the request to "save the full file contents one line at a time to a variable." 
Please reach out if you have questions.  Thursday should be almost 100% lab time.  It may offer a good time to ask!

For now, I will record 6 of 8 in the grade book, but I would like you to resubmit to get full credit.

Thanks.

Chris

**Comment by cethenmc** [comment]
Looks great.  You forgot to issue a reply to this Issue Ticket when it was ready for regrading.
